### ISSUE TITLE
`racs2_bridge_client`: Message initialization uses incorrect size

### ISSUE THREAD

**Issue by ivanperez-keera** [jaxa/racs2_bridge#3]
The following `InitMsg` call:

https://github.com/jaxa/racs2_bridge/blob/9077e0986c0dcc9ab29dff32a179f96b3ff44de5/cFS/Bridge/Client_C/apps/racs2_bridge_client/fsw/src/racs2_bridge_client.c#L321

uses an incorrect size `CFS_CHAR_ARR_MSG_LNGTH`. This causes memory to be overwritten in some circumstances.

The data structure `RACS2_BRIDGE_CLIENT_HkTelemetryPkt` has type `sample_hk_tlm_t`, whose length according to:

https://github.com/jaxa/racs2_bridge/blob/9077e0986c0dcc9ab29dff32a179f96b3ff44de5/cFS/Bridge/Client_C/apps/racs2_bridge_client/fsw/src/racs2_bridge_client_msg.h#L24-L33C9

should be `SAMPLE_APP_HK_TLM_LNGTH`.

**Comment by yuyuqq** [comment]
Issue #3 was resolved by incorporating pull request #9 as @ivanperez-keera suggested.
