### ISSUE TITLE
`racs2_bridge_client`: Use binary encoding instead of text

### ISSUE THREAD

**Issue by ivanperez-keera** [jaxa/racs2_bridge#4]
We seem to be seeing issues passing data of different types across the bridge. We think this is related to the choice of using text-based encoding:

https://github.com/jaxa/racs2_bridge/blob/9077e0986c0dcc9ab29dff32a179f96b3ff44de5/cFS/Bridge/Client_C/apps/racs2_bridge_client/fsw/src/racs2_bridge_client.c#L127

which is known to modify data. Changing this to binary, and adjusting the ROS 2 side accordingly here:

https://github.com/jaxa/racs2_bridge/blob/9077e0986c0dcc9ab29dff32a179f96b3ff44de5/ROS2/Bridge/Server_Python/bridge_py_s/bridge_py_s/bridge_py_s_node.py#L109

to something along the lines of:

```python
bytes_list = [elem.to_bytes(elem, byteorder='little') for elem in recv_message[32:-1]]
```

seems to solve the issue. I'm not sure if the byteorder is correct (please check), and the (-1) might have to be removed, based on the discussion in #2 .

**Comment by tt-saito** [comment]
Binary data is preferred over text format for bridge communications.

In cFS to ROS2 bridge communication, for the following codes on the cFS side,

https://github.com/jaxa/racs2_bridge/blob/f57939a9bf042877fd67439a2474211f5fe5bb10/cFS/Bridge/Client_C/apps/racs2_bridge_client/fsw/src/racs2_bridge_client.c#L127

`LWS_WRITE_TEXT` should be `LWS_WRITE_BINARY`, data storage in `g_bridge_msg_pkt` needs to be modified as binary format accordingly.

On the ROS2 side, the received data needs to be processed as binary data as @ivanperez-keera pointed out, I think the received data should be assigned to bytes_list as follows.

```
bytes_list = [bytes([elem]) for elem in recv_message[32:]]
```

**Comment by tt-saito** [comment]
For a message bridge from ROS2 to cFS, the following code:

https://github.com/jaxa/racs2_bridge/blob/f57939a9bf042877fd67439a2474211f5fe5bb10/cFS/Bridge/Client_C/apps/racs2_bridge_client/fsw/src/racs2_bridge_client.c#L98

should be processed assuming a binary format, not a text format, as shown below,

```
memcpy(RACS2_UserMsgPkt.body_data, (uint8_t*)in + RACS2_BRIDGE_HEADER_LENGTH, body_data_length);
```

**Comment by yuyuqq** [comment]
Close by pull request #10

**Comment by yuyuqq** [comment]
Close by pull request #10
